### ISSUE TITLE
July 2017

### ISSUE THREAD

**Issue by hzoo** [babel/proposals#19]
Just summarizing the updates from: https://github.com/tc39/agendas/blob/master/2017/07.md

> Can discuss changes as they pertain to Babel implementation (syntax).
> babel-polyfill implementation is https://github.com/zloirock/core-js

EDIT: made some issues for Babel updates

## New Proposals

- [x] [Binary AST 🙌 ](https://github.com/babel/proposals/issues/21): Stage 1
- [x] [Optional Catch Binding `try {} catch {} `](https://github.com/babel/proposals/issues/7): Stage 3
  - https://github.com/babel/babel/pull/6032
- [x] [Throw Expressions `throw new Error('')`](https://github.com/babel/proposals/issues/23): Stage 1

## Moving Forward

- [x] [BigInt `10n`](https://github.com/babel/proposals/issues/2): Stage 2 to Stage 3
  - [x] https://github.com/babel/babel/pull/6015 (we're not going to put in a stage preset given perf issues)
- [x] [Numeric Separators `1_000`](https://github.com/babel/proposals/issues/20): Stage 1 to Stage 2
  - https://github.com/babel/babel/pull/6071
- [x] [export-ns-from `export * as ns from 'mod'`](https://github.com/babel/proposals/issues/16): Stage 1 to Stage 2 (also ["consensus PR"](https://github.com/tc39/ecma262/pulls?q=is%3Aopen+is%3Apr+label%3A%22needs+consensus%22))
  - [x] https://github.com/babel/babel/issues/6075
- [x] [Class Fields `class A { #a = 1; b = 2 }`](https://github.com/babel/proposals/issues/12): Stage 2 to Stage 3
  - [x] https://github.com/babel/babel/issues/6073

## Needs work

- [export-default-from `export default from 'mod'`](https://github.com/babel/proposals/issues/17): Stayed at Stage 1
- [Decorators `@a class A{}`](https://github.com/babel/proposals/issues/11): Stayed at Stage 2
- [Optional Chaining `a?.b` ](https://github.com/babel/proposals/issues/18): Stayed at Stage 1

**Comment by hzoo** [comment]
Maybe we add here (and/or in each issue) the changes we need to make in each transform? Obviously if it's a new proposal we may need to implement something, and for proposals that progressed change the preset it's in and maybe some updates.

**Comment by littledan** [comment]
Private methods were introduced.

Decorators stayed at Stage 2 but with significant changes to semantics, for integration with fields and private, which the committee seemed mostly happy with except for the private part.

Optional chaining also has new draft semantics, but the committee seemed very sceptical of both the old and the new semantics.

Export-ns-from will be pursued as a needs-consensus PR, rather than with stages. For Babel purposes, it might make sense to put at Stage 3.

**Comment by littledan** [comment]
I believe Promise.prototype.finally reached Stage 3 as well. The semantics have changed slightly recently.

For core-js, I think the big need is BigInt, a polyfill. The rest are Babel/Bablyon changes.

**Comment by sricc** [comment]
I've never contributed to this project before but am interested in learning and helping where I can. Is there something that would be better suited for me to take a look at?

**Comment by hzoo** [comment]
- [ ] Class fields: The transform should be moved from the Stage 2 preset to the Stage 3 preset. And we should make the current "spec" mode the normal mode, and the normal mode the "loose" option.  This is since the current spec requires using defineProperty instead of a simple assignment, and that `class A { a; }` should compile into `a = undefined;`

**Comment by jridgewell** [comment]
@sricc: You could check out any of the `beginner-friendly` labelled issues: https://github.com/babel/babel/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner-friendly

**Comment by sricc** [comment]
@jridgewell Thanks, will check those out.

**Comment by Andarist** [comment]
> current spec requires using defineProperty instead of a simple assignment

@hzoo why `defineProperty` is required now? Im trying to see how they differ, if all descriptor options are set to `true`

**Comment by hzoo** [comment]
@Andarist https://github.com/babel/babel/pull/4544, https://github.com/babel/babel/issues/5056, https://github.com/babel/babel/pull/6076 https://twitter.com/BrendanEich/status/778342783031521280

**Comment by littledan** [comment]
We had a long debate about `=` vs `defineProperty` in TC39. The main way they differ, besides setting the descriptor options to true, is in calling setters: If a superclass defines a setter, `=` will call that setter. This can be good or bad, depending on what you expect for your code. Lots of people had different intuitions here, and we settled on one of the two, with the tiebreaker being that your code is more locally predictable and understandable if those setters aren't called.

**Comment by Andarist** [comment]
Totally makes sense and I believe you have chosen wisely ;) Always forgetting about getters/setters when thinking about the code. Thanks for the clarification.

**Comment by hzoo** [comment]
I think we finished everything ^ as of https://github.com/babel/babel/releases/tag/v7.0.0-beta.0, and we made an issue for throw expressions.

**Comment by hzoo** [comment]
Ok closing since we implemented everything here, and next meeting issue is up https://github.com/babel/proposals/issues/28
